[keyboard]
name = "cheapino_w"
product_name = "cheapino_w"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "esp32c3"
usb_enable = false

[matrix]
# Input and output pins are mandatory
row_pins = ["GPIO4", "GPIO5", "GPIO6", "GPIO2", "GPIO8", "GPIO9"]
col_pins = ["GPIO0", "GPIO1", "GPIO3", "GPIO7", "GPIO10", "GPIO20"]

# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation.
# Checkout doc here: https://rmk.rs/docs/user_guide/faq.html#my-matrix-is-row2col-the-matrix-doesn-t-work
# row2col = true

[layout]
rows = 6
cols = 6
layers = 4
keymap = [
    # ================= LAYER 0: Base =================
    [
        ["Q", "W", "E", "R", "T", "MT(Escape, LShift)"],
        ["A", "S", "D", "F", "LT(1, G)", "LCtrl"],
        ["Z", "X", "C", "V", "B", "LCtrl"],
        ["Y", "U", "I", "O", "P", "LT(1, Space)"],
        ["H", "J", "K", "L", "Semicolon", "MT(Enter, LAlt)"],
        ["N", "M", "LeftBracket", "RightBracket", "Slash", "Backspace"]
    ],

    # ================= LAYER 1: Numbers, Nav, BT =================
    [
        ["Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "_"],
        ["Tab", "Equal", "Minus", "Quote", "Backslash", "_"],
        ["Grave", "No", "No", "No", "No", "_"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "_"],
        ["PageUp", "Left", "Up", "Down", "Right", "_"],
        ["PageDown", "No", "No", "Comma", "Dot", "Delete"]
    ],

    # ================= LAYER 2: Empty =================
    [
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"]
    ],

    # ================= LAYER 3: Empty =================
    [
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_"]
    ]
]

[behavior.morse]
prior_idle_time = 120
hold_timeout = 230

[ble]
enabled = true
# Seconds of inactivity before entering deep sleep (0 = never)
# ble_sleep_timeout = 600