[layout]
rows = 6
cols = 6
layers = 3
layers_num = 3

# String mapping of the electronic matrix to physical keys
matrix_map = """
(0,0) (0,1) (0,2) (3,3) (3,4) (3,5)
(1,0) (1,1) (1,2) (4,3) (4,4) (4,5)
(2,0) (2,1) (2,2) (5,3) (5,4) (5,5)
(0,3) (1,3) (2,3) (3,0) (4,0) (5,0)
(0,4) (1,4) (2,4) (3,1) (4,1) (5,1)
(0,5) (1,5) (2,5) (3,2) (4,2) (5,2)
"""

# Base Layer (Layer 0) - Just the basics to get you typing
[[layer]]
name = "base_layer"
keys = """
Q      W      E      R      T      Y      U      I      O      P
A      S      D      F      G      H      J      K      L      SCLN
Z      X      C      V      B      N      M      COMM   DOT    SLSH
ESC    SPC    TAB                  ENT    BSPC   MO(1)
"""

# Blank Layer 1 (Accessible via Vial)
[[layer]]
name = "lower_layer"
keys = """
_      _      _      _      _      _      _      _      _      _
_      _      _      _      _      _      _      _      _      _
_      _      _      _      _      _      _      _      _      _
_      _      _                    _      _      _
"""

# Blank Layer 2 (Accessible via Vial)
[[layer]]
name = "raise_layer"
keys = """
_      _      _      _      _      _      _      _      _      _
_      _      _      _      _      _      _      _      _      _
_      _      _      _      _      _      _      _      _      _
_      _      _                    _      _      _
"""
