[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.objcopy]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = ["objcopy", "--release", "--", "-O", "ihex", "cheapino_w.hex"]
dependencies = ["install-llvm-tools"]

[tasks.uf2]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "cheapino_w.hex",
    "--output-path",
    "cheapino_w.uf2",
    "--family",
    "esp32c3",
]
dependencies = ["objcopy"]

