#![no_std]
#![no_main]

use esp_alloc as _;
use esp_backtrace as _;

::esp_bootloader_esp_idf::esp_app_desc!();

// Vial config generated by build.rs from vial.json
include!(concat!(env!("OUT_DIR"), "/config_generated.rs"));

// Matrix dimensions from keyboard.toml
const ROW: usize = 6;
const COL: usize = 6;
const NUM_LAYER: usize = 4;

// Default keymap matching keyboard.toml
fn get_default_keymap() -> [[[::rmk::types::action::KeyAction; COL]; ROW]; NUM_LAYER] {
    use ::rmk::types::action::KeyAction;
    use ::rmk::types::keycode::KeyCode::*;
    const T: KeyAction = KeyAction::Transparent;
    const N: KeyAction = KeyAction::No;
    let k = |kc| KeyAction::Single(::rmk::types::action::Action::Key(kc));
    [
        // Layer 0: Base QWERTY
        [
            [k(Q),         k(W),     k(E),     k(R),    k(T),         k(Space)],
            [k(A),         k(S),     k(D),     k(F),    k(G),         k(Tab)],
            [k(Z),         k(X),     k(C),     k(V),    k(B),         k(LCtrl)],
            [k(Y),         k(U),     k(I),     k(O),    k(P),         k(Enter)],
            [k(H),         k(J),     k(K),     k(L),    k(Semicolon), k(Backspace)],
            [k(N),         k(M),     k(Comma), k(Dot),  k(Slash),     k(LAlt)],
        ],
        // Layer 1-3: Empty
        [[T; COL]; ROW],
        [[T; COL]; ROW],
        [[T; COL]; ROW],
    ]
}

// =============================================================================
// Cheapino bidirectional matrix scan map
// =============================================================================
//
// Pin index assignments (12 pins total):
//   0: GPIO4  (row0)     6: GPIO0  (col0)
//   1: GPIO5  (row1)     7: GPIO1  (col1)
//   2: GPIO6  (row2)     8: GPIO3  (col2)
//   3: GPIO2  (row3)     9: GPIO7  (col3)
//   4: GPIO8  (row4)    10: GPIO10 (col4)
//   5: GPIO9  (row5)    11: GPIO20 (col5)
//
// Each entry: (out_pin_idx, in_pin_idx)
// Scanning: out drives HIGH, in reads (pull-down) — if HIGH, key pressed

const SCAN_MAP: [[(usize, usize); COL]; ROW] = [
    // Row 0 (left): Q  W  E  R  T  Space
    [(11,3), (3,10), (10,3), (3,9), (9,3), (3,11)],
    // Row 1 (left): A  S  D  F  G  Tab
    [(11,4), (4,10), (10,4), (4,9), (9,4), (4,11)],
    // Row 2 (left): Z  X  C  V  B  LCtrl
    [(11,5), (5,10), (10,5), (5,9), (9,5), (5,11)],
    // Row 3 (right): Y  U  I  O  P  Enter
    [(6,0),  (0,6),  (7,0),  (0,7),  (8,0),  (0,8)],
    // Row 4 (right): H  J  K  L  ;  Backspace
    [(6,1),  (1,6),  (7,1),  (1,7),  (8,1),  (1,8)],
    // Row 5 (right): N  M  ,  .  /  LAlt
    [(6,2),  (2,6),  (7,2),  (2,7),  (8,2),  (2,8)],
];

#[esp_rtos::main]
async fn main(_s: ::embassy_executor::Spawner) {
    // ---- Chip init (matches rmk macro generated code for esp32c3 BLE) ----
    ::esp_println::logger::init_logger_from_env();
    let p = ::esp_hal::init(
        ::esp_hal::Config::default()
            .with_cpu_clock(::esp_hal::clock::CpuClock::max()),
    );
    ::esp_alloc::heap_allocator!(size: 72 * 1024);
    let timg0 = ::esp_hal::timer::timg::TimerGroup::new(p.TIMG0);
    let software_interrupt =
        ::esp_hal::interrupt::software::SoftwareInterruptControl::new(p.SW_INTERRUPT);
    ::esp_rtos::start(timg0.timer0, software_interrupt.software_interrupt0);
    let _trng_source = ::esp_hal::rng::TrngSource::new(p.RNG, p.ADC1);
    let mut rng = ::esp_hal::rng::Trng::try_new().unwrap();

    // ---- BLE ----
    static RADIO: ::static_cell::StaticCell<::esp_radio::Controller<'static>> =
        ::static_cell::StaticCell::new();
    let radio = RADIO.init(::esp_radio::init().unwrap());
    let bluetooth = p.BT;
    let connector =
        ::esp_radio::ble::controller::BleConnector::new(radio, bluetooth, Default::default())
            .unwrap();
    let controller: ::bt_hci::controller::ExternalController<_, 64> =
        ::bt_hci::controller::ExternalController::new(connector);
    let ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7];
    let mut host_resources = ::rmk::HostResources::new();
    let stack =
        ::rmk::ble::build_ble_stack(controller, ble_addr, &mut rng, &mut host_resources).await;

    // ---- Flash + Storage ----
    let flash = ::esp_storage::FlashStorage::new(p.FLASH);
    let flash = ::rmk::storage::async_flash_wrapper(flash);
    let storage_config = ::rmk::config::StorageConfig {
        start_addr: 0x3f0000,
        num_sectors: 16,
        ..Default::default()
    };

    // ---- RMK Config ----
    let vial_config =
        ::rmk::config::VialConfig::new(VIAL_KEYBOARD_ID, VIAL_KEYBOARD_DEF, &[(0, 0), (1, 1)]);
    let rmk_config = ::rmk::config::RmkConfig {
        vial_config,
        storage_config,
        ..Default::default()
    };

    // ---- Keymap + Storage ----
    let mut keymap_data = ::rmk::keymap::KeymapData::new(get_default_keymap());
    let mut behavior_config = ::rmk::config::BehaviorConfig::default();
    let per_key_config = ::rmk::config::PositionalConfig::default();
    let (keymap, mut storage) = ::rmk::initialize_keymap_and_storage(
        &mut keymap_data,
        flash,
        &storage_config,
        &mut behavior_config,
        &per_key_config,
    )
    .await;

    // ---- Keyboard ----
    let mut keyboard = ::rmk::keyboard::Keyboard::new(&keymap);

    // ---- Flex pins for bidirectional scanning ----
    let mut pins: [::esp_hal::gpio::Flex; 12] = [
        ::esp_hal::gpio::Flex::new(p.GPIO4),  // 0: row0
        ::esp_hal::gpio::Flex::new(p.GPIO5),  // 1: row1
        ::esp_hal::gpio::Flex::new(p.GPIO6),  // 2: row2
        ::esp_hal::gpio::Flex::new(p.GPIO2),  // 3: row3
        ::esp_hal::gpio::Flex::new(p.GPIO8),  // 4: row4
        ::esp_hal::gpio::Flex::new(p.GPIO9),  // 5: row5
        ::esp_hal::gpio::Flex::new(p.GPIO0),  // 6: col0
        ::esp_hal::gpio::Flex::new(p.GPIO1),  // 7: col1
        ::esp_hal::gpio::Flex::new(p.GPIO3),  // 8: col2
        ::esp_hal::gpio::Flex::new(p.GPIO7),  // 9: col3
        ::esp_hal::gpio::Flex::new(p.GPIO10), // 10: col4
        ::esp_hal::gpio::Flex::new(p.GPIO20), // 11: col5
    ];

    // Init all pins as inputs with pull-down
    for pin in pins.iter_mut() {
        pin.set_output_enable(false);
        pin.apply_input_config(
            &::esp_hal::gpio::InputConfig::default()
                .with_pull(::esp_hal::gpio::Pull::Down),
        );
        pin.set_input_enable(true);
    }

    // ---- Run all tasks concurrently ----
    use ::rmk::input_device::Runnable;
    ::rmk::embassy_futures::join::join3(
        bidirectional_scan(&mut pins),
        keyboard.run(),
        ::rmk::run_rmk(&keymap, &stack, &mut storage, rmk_config),
    )
    .await;
}

/// Bidirectional matrix scanner for Cheapino
///
/// Scans all 36 key positions by driving each output pin HIGH one at a time
/// and reading the corresponding input pin. Debounces and publishes events.
async fn bidirectional_scan(pins: &mut [::esp_hal::gpio::Flex<'_>; 12]) -> ! {
    use ::rmk::debounce::DebouncerTrait;

    let mut debouncer = ::rmk::debounce::default_debouncer::DefaultDebouncer::<ROW, COL>::new();
    let mut key_state = [[::rmk::matrix::KeyState::new(); COL]; ROW];

    loop {
        for row in 0..ROW {
            for col in 0..COL {
                let (out_idx, in_idx) = SCAN_MAP[row][col];

                // Drive output HIGH
                pins[out_idx].set_input_enable(false);
                pins[out_idx].set_low();
                pins[out_idx].set_output_enable(true);
                pins[out_idx].set_high();

                // Brief settle time
                ::rmk::embassy_time::Timer::after_micros(1).await;

                // Read input
                let pressed = pins[in_idx].is_high();

                // Restore output pin to input mode
                pins[out_idx].set_low();
                pins[out_idx].set_output_enable(false);
                pins[out_idx].apply_input_config(
                    &::esp_hal::gpio::InputConfig::default()
                        .with_pull(::esp_hal::gpio::Pull::Down),
                );
                pins[out_idx].set_input_enable(true);

                // Brief settle after restoring
                ::rmk::embassy_time::Timer::after_micros(1).await;

                // Debounce
                let debounce_state = debouncer.detect_change_with_debounce(
                    row,
                    col,
                    pressed,
                    &key_state[row][col],
                );

                if let ::rmk::debounce::DebounceState::Debounced = debounce_state {
                    key_state[row][col].toggle_pressed();
                    let event = ::rmk::event::KeyboardEvent::key(
                        row as u8,
                        col as u8,
                        key_state[row][col].pressed,
                    );
                    ::rmk::event::publish_event_async(event).await;
                }
            }
        }

        // ~1ms scan interval for ~1000Hz polling
        ::rmk::embassy_time::Timer::after_millis(1).await;
    }
}
