#![no_std]
#![no_main]

use esp_alloc as _;
use esp_backtrace as _;

::esp_bootloader_esp_idf::esp_app_desc!();

// Vial config generated by build.rs from vial.json
include!(concat!(env!("OUT_DIR"), "/config_generated.rs"));

// Matrix dimensions from keyboard.toml
const ROW: usize = 6;
const COL: usize = 6;
const NUM_LAYER: usize = 4;

// Default keymap from quantum cheapino.vil
fn get_default_keymap() -> [[[::rmk::types::action::KeyAction; COL]; ROW]; NUM_LAYER] {
    use ::rmk::types::action::{Action, KeyAction, MorseProfile};
    use ::rmk::types::keycode::KeyCode::{self, *};
    const TRNS: KeyAction = KeyAction::Transparent;
    const NO: KeyAction = KeyAction::No;
    let k = |kc| KeyAction::Single(Action::Key(kc));
    let mt = |tap_kc: KeyCode, hold_kc: KeyCode| KeyAction::TapHold(
        Action::Key(tap_kc), Action::Key(hold_kc), MorseProfile::default(),
    );
    let lt = |layer, tap_kc| KeyAction::TapHold(
        Action::Key(tap_kc), Action::LayerOn(layer), MorseProfile::default(),
    );
    [
        // Layer 0: Base
        [
            [k(Q),    k(W),     k(E),          k(R),     k(T),          mt(Escape, LShift)],
            [k(A),    k(S),     k(D),          k(F),     lt(1, G),      k(LCtrl)],
            [k(Z),    k(X),     k(C),          k(V),     k(B),          k(LCtrl)],
            [k(Y),    k(U),     k(I),          k(O),     k(P),          lt(1, Space)],
            [k(H),    k(J),     k(K),          k(L),     k(Semicolon), mt(Enter, LAlt)],
            [k(N),    k(M),     k(LeftBracket), k(RightBracket), k(Slash), k(Backspace)],
        ],
        // Layer 1: Numbers, Navigation, BT
        [
            [k(Kc1),      k(Kc2),    k(Kc3),    k(Kc4),    k(Kc5),       TRNS],
            [k(Tab),      k(Equal),  k(Minus),  k(Quote),  k(Backslash), TRNS],
            [k(Grave),    NO,        NO,        NO,        NO,         TRNS],
            [k(Kc6),      k(Kc7),    k(Kc8),    k(Kc9),    k(Kc0),       TRNS],
            [k(PageUp),   k(Left),   k(Up),     k(Down),   k(Right),      TRNS],
            [k(PageDown), NO,        NO,        k(Comma),  k(Dot),        k(Delete)],
        ],
        // Layers 2-3: Transparent
        [[TRNS; COL]; ROW],
        [[TRNS; COL]; ROW],
    ]
}

// Entry structure: (out_pin_idx, in_pin_idx)
const SCAN_MAP: [[(usize, usize); COL]; ROW] = [
    // Row 0 (left): Q  W  E  R  T  Space
    [(11, 3), (3, 10), (10, 3), (3, 9), (9, 3), (5, 11)],
    // Row 1 (left): A  S  D  F  G  Tab
    [(11, 4), (4, 10), (10, 4), (4, 9), (9, 4), (4, 11)],
    // Row 2 (left): Z  X  C  V  B  LCtrl
    [(11, 5), (5, 10), (10, 5), (5, 9), (9, 5), (3, 11)],
    // Row 3 (right): Y  U  I  O  P  Enter
    [(6, 0), (0, 6), (7, 0), (0, 7), (8, 0), (0, 8)],
    // Row 4 (right): H  J  K  L  ;  Backspace
    [(6, 1), (1, 6), (7, 1), (1, 7), (8, 1), (1, 8)],
    // Row 5 (right): N  M  ,  .  /  LAlt
    [(6, 2), (2, 6), (7, 2), (2, 7), (8, 2), (2, 8)],
];

#[esp_rtos::main]
async fn main(_s: ::embassy_executor::Spawner) {
    ::esp_println::logger::init_logger_from_env();
    let p = ::esp_hal::init(
        ::esp_hal::Config::default()
            .with_cpu_clock(::esp_hal::clock::CpuClock::_80MHz),
    );

    // Disable brown-out detector to handle battery current spikes safely
    unsafe {
        let rtc_brown_out_reg = 0x600080D4 as *mut u32;
        let val = core::ptr::read_volatile(rtc_brown_out_reg);
        core::ptr::write_volatile(rtc_brown_out_reg, val & !(1 << 30));
    }

    ::esp_alloc::heap_allocator!(size: 72 * 1024);
    let timg0 = ::esp_hal::timer::timg::TimerGroup::new(p.TIMG0);
    let software_interrupt =
        ::esp_hal::interrupt::software::SoftwareInterruptControl::new(p.SW_INTERRUPT);
    ::esp_rtos::start(timg0.timer0, software_interrupt.software_interrupt0);
    let _trng_source = ::esp_hal::rng::TrngSource::new(p.RNG, p.ADC1);
    let mut rng = ::esp_hal::rng::Trng::try_new().unwrap();

    // ---- BLE ----
    static RADIO: ::static_cell::StaticCell<::esp_radio::Controller<'static>> =
        ::static_cell::StaticCell::new();
    let radio = RADIO.init(::esp_radio::init().unwrap());
    let bluetooth = p.BT;
    let connector =
        ::esp_radio::ble::controller::BleConnector::new(radio, bluetooth, Default::default())
            .unwrap();
    let controller: ::bt_hci::controller::ExternalController<_, 64> =
        ::bt_hci::controller::ExternalController::new(connector);
    let ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7];
    let mut host_resources = ::rmk::HostResources::new();
    let stack =
        ::rmk::ble::build_ble_stack(controller, ble_addr, &mut rng, &mut host_resources).await;

    // ---- Flash + Storage ----
    let flash = ::esp_storage::FlashStorage::new(p.FLASH);
    let flash = ::rmk::storage::async_flash_wrapper(flash);
    let storage_config = ::rmk::config::StorageConfig {
        start_addr: 0x3f0000,
        num_sectors: 16,
        ..Default::default()
    };

    // ---- RMK Config ----
    let vial_config =
        ::rmk::config::VialConfig::new(VIAL_KEYBOARD_ID, VIAL_KEYBOARD_DEF, &[(0, 0), (1, 1)]);
    let rmk_config = ::rmk::config::RmkConfig {
        vial_config,
        storage_config,
        ..Default::default()
    };

    // ---- Keymap + Storage ----
    let mut default_keymap = get_default_keymap();
    let mut behavior_config = ::rmk::config::BehaviorConfig::default();
    let mut per_key_config = ::rmk::config::PositionalConfig::default();
    let (keymap, mut storage) = ::rmk::initialize_keymap_and_storage(
        &mut default_keymap,
        flash,
        &storage_config,
        &mut behavior_config,
        &mut per_key_config,
    )
    .await;

    // ---- Keyboard ----
    let mut keyboard = ::rmk::keyboard::Keyboard::new(&keymap);

    // ---- Flex pins for bidirectional scanning ----
    let pins: [::esp_hal::gpio::Flex; 12] = [
        ::esp_hal::gpio::Flex::new(p.GPIO4),  // 0
        ::esp_hal::gpio::Flex::new(p.GPIO5),  // 1
        ::esp_hal::gpio::Flex::new(p.GPIO6),  // 2
        ::esp_hal::gpio::Flex::new(p.GPIO2),  // 3
        ::esp_hal::gpio::Flex::new(p.GPIO8),  // 4
        ::esp_hal::gpio::Flex::new(p.GPIO9),  // 5
        ::esp_hal::gpio::Flex::new(p.GPIO0),  // 6
        ::esp_hal::gpio::Flex::new(p.GPIO1),  // 7
        ::esp_hal::gpio::Flex::new(p.GPIO3),  // 8
        ::esp_hal::gpio::Flex::new(p.GPIO7),  // 9
        ::esp_hal::gpio::Flex::new(p.GPIO10), // 10
        ::esp_hal::gpio::Flex::new(p.GPIO20), // 11
    ];

    // Clean, static allocation for the background executor task
    static PINS: ::static_cell::StaticCell<[::esp_hal::gpio::Flex<'static>; 12]> = 
        ::static_cell::StaticCell::new();
    let pins_ref = PINS.init(pins);

    // Spawn scanning runtime engine asynchronously onto background runner stack
    _s.spawn(scanner_task(pins_ref)).unwrap();

    // Concurrently handle keyboard processing loop and active BLE system stack
    use ::rmk::input_device::Runnable;
    ::rmk::embassy_futures::join::join(
        keyboard.run(),
        ::rmk::run_rmk(&keymap, &stack, &mut storage, rmk_config),
    )
    .await;
}

#[embassy_executor::task]
async fn scanner_task(pins: &'static mut [::esp_hal::gpio::Flex<'static>; 12]) {
    bidirectional_scan(pins).await;
}

/// High-Impedance Safe Open-Drain matrix check. Prevents GPIO drive heating loops.
async fn full_scan(
    pins: &mut [::esp_hal::gpio::Flex<'_>; 12],
    debouncer: &mut ::rmk::debounce::default_debouncer::DefaultDebouncer<ROW, COL>,
    key_state: &mut [[::rmk::matrix::KeyState; COL]; ROW],
) -> bool {
    use ::rmk::debounce::DebouncerTrait;
    let mut any_pressed = false;

    // Disconnect ALL pins to an completely unpulled floating Hi-Z input configuration
    for pin in pins.iter_mut() {
        pin.set_output_enable(false);
        pin.apply_input_config(&::esp_hal::gpio::InputConfig::default().with_pull(::esp_hal::gpio::Pull::None));
        pin.set_input_enable(true);
    }

    for row in 0..ROW {
        for col in 0..COL {
            let (out_idx, in_idx) = SCAN_MAP[row][col];
            if out_idx == in_idx { continue; }

            // Turn on pull-up internal gate strictly on target line input point
            pins[in_idx].apply_input_config(
                &::esp_hal::gpio::InputConfig::default().with_pull(::esp_hal::gpio::Pull::Up),
            );

            // Active low scan segment configuration drive step
            pins[out_idx].set_input_enable(false);
            pins[out_idx].set_low();
            pins[out_idx].set_output_enable(true);

            // Give voltage capacitance a safe microsecond to settle down cleanly
            ::embassy_time::Timer::after_micros(10).await;

            let pressed = pins[in_idx].is_low();

            // Clear configuration immediately back to disconnected floating states
            pins[out_idx].set_output_enable(false);
            pins[out_idx].apply_input_config(&::esp_hal::gpio::InputConfig::default().with_pull(::esp_hal::gpio::Pull::None));
            pins[out_idx].set_input_enable(true);
            pins[in_idx].apply_input_config(&::esp_hal::gpio::InputConfig::default().with_pull(::esp_hal::gpio::Pull::None));

            if pressed {
                any_pressed = true;
            }

            let debounce_state = debouncer.detect_change_with_debounce(
                row, col, pressed, &key_state[row][col],
            );

            if let ::rmk::debounce::DebounceState::Debounced = debounce_state {
                key_state[row][col].toggle_pressed();
                let event = ::rmk::event::KeyboardEvent::key(
                    row as u8, col as u8, key_state[row][col].pressed,
                );
                ::rmk::channel::KEY_EVENT_CHANNEL.send(event).await;
            }
        }
    }
    any_pressed
}

async fn interrupt_sleep(pins: &mut [::esp_hal::gpio::Flex<'_>; 12]) {
    let pull_up = ::esp_hal::gpio::InputConfig::default().with_pull(::esp_hal::gpio::Pull::Up);
    let (rows, cols) = pins.split_at_mut(6);

    for c in cols.iter_mut() {
        c.set_input_enable(false);
        c.set_low();
        c.set_output_enable(true);
    }

    let (r0, rest) = rows.split_at_mut(1);
    let (r1, rest) = rest.split_at_mut(1);
    let (r2, rest) = rest.split_at_mut(1);
    let (r3, rest) = rest.split_at_mut(1);
    let (r4, r5) = rest.split_at_mut(1);

    use ::rmk::embassy_futures::select::select;
    select(
        select(
            select(r0[0].wait_for_falling_edge(), r1[0].wait_for_falling_edge()),
            select(r2[0].wait_for_falling_edge(), r3[0].wait_for_falling_edge()),
        ),
        select(r4[0].wait_for_falling_edge(), r5[0].wait_for_falling_edge()),
    )
    .await;

    for c in cols.iter_mut() {
        c.set_output_enable(false);
        c.apply_input_config(&pull_up);
        c.set_input_enable(true);
    }
}

async fn bidirectional_scan(pins: &mut [::esp_hal::gpio::Flex<'_>; 12]) -> ! {
    let mut debouncer = ::rmk::debounce::default_debouncer::DefaultDebouncer::<ROW, COL>::new();
    let mut key_state = [[::rmk::matrix::KeyState::new(); COL]; ROW];
    let mut idle_scans: u32 = 0;

    loop {
        // Drop into hardware deep sleep after 3 seconds of desk inactivity (~1500 scans)
        if idle_scans >= 61_500 {
            // 1500 active scans (3s) + 60000 idle scans at 100Hz (10min) = deep sleep
            interrupt_sleep(pins).await;
            full_scan(pins, &mut debouncer, &mut key_state).await;
            idle_scans = 0;
        } else {
            let any_pressed = full_scan(pins, &mut debouncer, &mut key_state).await;

            if any_pressed {
                idle_scans = 0;
            } else {
                idle_scans = idle_scans.saturating_add(1);
            }

            let sleep_ms = if idle_scans < 1_500 {
                2   // Active: 500Hz (first 3s)
            } else {
                20  // Idle: 50Hz — responsive enough for taps, much less CPU heat
            };
            ::embassy_time::Timer::after_millis(sleep_ms).await;
        }
    }
}
